apiVersion: v1
kind: Service
metadata:
  name: resume-summary-service
spec:
  selector:
    app: resume-summary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
